### ISSUE TITLE
考虑做成GUI吗

### ISSUE THREAD

**Issue by coding-ax** [cutelittletiantian/python-for-office#1]

**Comment by cutelittletiantian** [comment]
以后是有可能的，像整理文档这种繁琐扎心的事情很多人都要面对，所以我觉得这个仓库的内容是对他们有帮助的。但是因为具体的业务千差万别，在做成GUI之前我先要调研清楚一些通用、普适的需求再去具体实现GUI界面。
It'll be implemented later. I realize many people have some relavant problems in their daily work, such as repeatedly organizing their documents all the time, so I believe they will get something through this repository. However, since their work dramatically varies, it'll take much more time to gather and analyze some common requirements before I finally make them GUI.
